CREATE TABLE USERS (  ID       INT,  USERNAME VARCHAR(20),  PASSWORD VARCHAR(20));

CREATE TABLE ROLES (  ID   INT,  NAME VARCHAR(20));

CREATE TABLE USERS_ROLES (  USER_ID INT,  ROLE_ID INT);

INSERT INTO USERS (ID, USERNAME, PASSWORD) VALUES (1, 'admin', 'geheim');
INSERT INTO USERS (ID, USERNAME, PASSWORD) VALUES (2, 'user', 'geheim');
INSERT INTO USERS (ID, USERNAME, PASSWORD) VALUES (3, 'guest', 'geheim');
INSERT INTO USERS (ID, USERNAME, PASSWORD) VALUES (4, 'anon', 'geheim');

INSERT INTO ROLES (ID, NAME) VALUES (1, 'admin');
INSERT INTO ROLES (ID, NAME) VALUES (2, 'user');
INSERT INTO ROLES (ID, NAME) VALUES (3, 'guest');
INSERT INTO ROLES (ID, NAME) VALUES (3, 'anon');

INSERT INTO USERS_ROLES (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO USERS_ROLES (USER_ID, ROLE_ID) VALUES (2, 2);
INSERT INTO USERS_ROLES (USER_ID, ROLE_ID) VALUES (3, 3);
INSERT INTO USERS_ROLES (USER_ID, ROLE_ID) VALUES (4, 4);
